feat(passbolt): Add chart
cnieg/helm-charts pull request #37
Opened 2021-01-21 15:03 UTC by Thomah

2021-01-22 07:42 UTC, audig approved these changes

2021-01-22 07:45 UTC, audig requested changes
Serait-il possible d'ajouter une dépendance à un chart externe mariadb, pour que le chart soit autportant avec sa base de données ?

2021-01-22 07:55 UTC, Thomah commented
> 
> 
> Serait-il possible d'ajouter une dépendance à un chart externe mariadb, pour que le chart soit autportant avec sa base de données ?

Oui je m'en occupe. Ça validera le workflow comme ça :)

2021-01-27 13:54 UTC, arnou requested changes
Quelques retours ligne en fin de fichiers semblent encore manquer

2021-01-27 13:54 UTC, arnou commented on charts/passbolt/templates/pvc.yaml
> +{{- end }}
```suggestion
{{- end }}

```

2021-01-27 13:54 UTC, arnou commented on charts/passbolt/templates/pdb.yaml
> +{{- end }}
```suggestion
{{- end }}

```

2021-01-27 14:01 UTC, Thomah commented on charts/passbolt/templates/deployment.yaml
> +      {{- end }}
Ajout retour à la ligne sur `deployment.yaml`
```suggestion
      {{- end }}

```

2021-01-27 16:17 UTC, arnou approved these changes

2021-01-27 16:53 UTC, audig approved these changes

2021-01-27 16:54 UTC, merged