#70 - email configuration
cnieg/helm-charts pull request #72
Opened 2022-03-14 13:45 UTC by tavoda

Passbolt chart changes:
- Email configuration with env variables in deployment
- Upgrade ingress to new kubernetes api version
- Readme update for passbolt

2022-03-14 15:40 UTC, Thomah requested changes
Hi @tavoda 

Thanks for the PR ! There are just a few things that needs to be taken care of before merging. Please checkout the comments for details.

Also we need to increment `version` in `Chart.yaml` to make the release work. Can you update to `1.1.3` please ?

2022-03-14 15:40 UTC, Thomah commented on charts/passbolt/templates/deployment.yaml
> +              value: {{ .Values.email.port }}
Be careful : you must always use a string for environment values. 

You may replace this section with :
```
- name: EMAIL_TRANSPORT_DEFAULT_PORT
  value: "{{ .Values.email.port }}"
```

2022-03-14 15:40 UTC, Thomah commented on charts/passbolt/templates/deployment.yaml
> +              value: {{ .Values.email.timeout }}
Same as previous comment

2022-03-14 15:40 UTC, Thomah commented on charts/passbolt/templates/ingress.yaml
> +  ingressClassName: {{ .Values.ingress.className }}
`ingressClassName` is not required if it's defined on the cluster level.

You should surround this line with a condition like
```
{{- if .Values.ingress.ingressClassName }}
```
in order to use the ingress class by default

2022-03-14 15:40 UTC, Thomah commented on charts/passbolt/templates/ingress.yaml
> +apiVersion: networking.k8s.io/v1
In Kubernetes 1.14, there is no kind Ingress in this API version.

Please keep v1beta1 or add an other test on `.Capabilities.KubeVersion.GitVersion`. If you choose the last option, you also need to adapt the spec below.

Checkout this comment for details : https://github.com/kubernetes/kubernetes/issues/90077#issuecomment-718778960

2022-03-15 08:41 UTC, tavoda commented
Fixed in 2nd commit, hope everything fixed :crossed_fingers:

2022-03-15 10:57 UTC, Thomah commented
Looks good to me 😃

Can you just increment version in Chart.yaml to 1.1.3 please ? The release will fail if not.

2022-03-15 11:04 UTC, tavoda commented
My first helm chart PR, I'm not aware of this details and dependencies. Thanks for your help. Done

2022-03-15 13:52 UTC, Thomah approved these changes

2022-03-15 13:58 UTC, merged

2022-03-15 13:59 UTC, Thomah commented
> My first helm chart PR, I'm not aware of this details and dependencies. Thanks for your help. Done

Don't mind it. Thanks for your contribution !